name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Setup
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install npm dependencies
        run: npm install
      - name: Run test script
        run: npm test

  DeployDev:
    name: Deploy to Dev
    # if: github.event_name == 'pull_request'
  if: github.event.ref == 'refs/heads/development'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo We are deploying on development!

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/master'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo We are deploying on staging!

  DeployProd:
    name: Deploy to Production
    needs: [ DeployStaging ]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo We are deploying on production!
